version: '3.8'

services:
  # Base de Datos con PostGIS Integrado
  # db:
  #   image: postgis/postgis:15-3.3-alpine
  #   container_name: SIGEL-db
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=admin
  #     - POSTGRES_DB=SIGEL
  #   ports:
  #     - "5434:5432" # Mapeado a 5434 para evitar conflicto con tu Postgres local o anterior
  #   volumes:
  #     - C:\Users\support\Documents\sigel_db_data:/var/lib/postgresql/data
  #   networks:
  #     - SIGEL-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: SIGEL-backend
    ports:
      - "8002:8001"
    # depends_on:
    #   - db
    environment:
      - PORT=8001
      - PYTHONUNBUFFERED=1
      # Ahora apunta al contenedor 'db' interno
      # Ahora apunta al PostgreSQL de Windows
      - DATABASE_URL=postgresql+asyncpg://postgres:admin@host.docker.internal:5432/SIGEL
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
    restart: unless-stopped
    networks:
      - SIGEL-network
    healthcheck:
      test: [ "CMD-SHELL", "python -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:8001/health\")'" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: SIGEL-frontend
    ports:
      - "3002:80"
    # depends_on:
    #   - backend
    restart: unless-stopped
    networks:
      - SIGEL-network
    volumes:
      - ./frontend/public:/usr/share/nginx/html/public
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1/" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  SIGEL-network:
    driver: bridge

volumes:
  sigel_db_data:
