version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: micancha-db-local
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: BBDD_micancha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: micancha-pgadmin-local
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@micancha.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data_local:
